//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class carroCompra
    {
        public int idRecord { get; set; }
        public string idCarrito { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> Conteo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
