//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class catCarrera
    {
        public int idCarrera { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idNivelEstudio { get; set; }
    }
}
