//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDireccionUsuario
    {
        public int idRegistro { get; set; }
        public Nullable<int> idMiembro { get; set; }
        public string DireccionL1 { get; set; }
        public string DireccionL2 { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public Nullable<int> CP { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    }
}
