//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleOrden
    {
        public int idOrdenDetalle { get; set; }
        public Nullable<int> idOrden { get; set; }
        public string idProducto { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    }
}
