//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class miembro
    {
        public int idMiembro { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string DireccionL1 { get; set; }
        public string DireccionL2 { get; set; }
        public Nullable<int> CP { get; set; }
        public string idAspNetUsers { get; set; }
        public Nullable<int> idTipo { get; set; }
    }
}
