//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdTareasEntities : DbContext
    {
        public bdTareasEntities()
            : base("name=bdTareasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carroCompra> carroCompra { get; set; }
        public virtual DbSet<catCarrera> catCarrera { get; set; }
        public virtual DbSet<catDireccionUsuario> catDireccionUsuario { get; set; }
        public virtual DbSet<catNivelEstudio> catNivelEstudio { get; set; }
        public virtual DbSet<catTipo> catTipo { get; set; }
        public virtual DbSet<catTipoProducto> catTipoProducto { get; set; }
        public virtual DbSet<detalleOrden> detalleOrden { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<miembro> miembro { get; set; }
        public virtual DbSet<orden> orden { get; set; }
    }
}
