//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int idOrden { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public Nullable<int> CP { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<bool> OrdenPagada { get; set; }
    }
}
