//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ADODataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public string idProducto { get; set; }
        public Nullable<int> idCarrera { get; set; }
        public Nullable<int> idTipoProducto { get; set; }
        public string nombreProducto { get; set; }
        public string descCorta { get; set; }
        public string descLargaContenido { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<bool> disponible { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string tags { get; set; }
        public Nullable<bool> comentarios { get; set; }
    }
}
